### ISSUE TITLE
Improvements for Android

### ISSUE THREAD

**Issue by bryanjos** [eoinsha/JavaPhoenixChannels#1]
Hi, nice work on this library! I was able to confirm that it still works for the latest version of Phoenix. When I was trying it with a new Android project, I ran into the dex method limit. I ended up deleting SimpleCliTest.groovy and making the groovy dependency only for the tests and that got it to work. I can send a PR with the change if needed. Here is the Android demo project I created using this: https://github.com/bryanjos/AndroidPhoenixDemo

Also, since Phoenix is nearing 1.0, maybe putting together a release would be helpful? For the demo project above, I just used jitpack.io with the fork I created to get it working. Maybe making a tag here and doing the same would be sufficient for now?

**Comment by eoinsha** [comment]
Hi Bryan,
Thanks. I am hoping to work soon on refinements to make the library more
robust, cover all cases and release so there's a stable version to work
with Phoenix 1.0.
I also came across the dex limit in the sample app I started for this. I
can't recall exactly, but I believe the exclusion of the transitive
groovy-all dependency resolved it.
You can see that here but I'd like to see your PR too!
https://github.com/eoinsha/PhoenixChatAndroid/blob/master/app/build.gradle

If you are willing to contribute further, that would also be a great help :)
Eoin

**Comment by bryanjos** [comment]
Hi Eoin. I didn't think to do that, but that makes sense. I will send make a PR with what I have. And I would love to contribute further when possible.

**Comment by eoinsha** [comment]
Great, thanks.
I understand it's difficult for people to get time to contribute Java
client support when everyone would rather be working in Elixir!
Any contributions are welcome.
Eoin

**Comment by bryanjos** [comment]
Closing this. I'll be happy to contribute if I run across anything or if there are some issues that come up.
