### ISSUE TITLE
Auto reconnect keeps trying even after a disconnect

### ISSUE THREAD

**Issue by papylhomme** [eoinsha/JavaPhoenixChannels#17]
I'm writing an application interfacing with multiple phoenix servers and I encountered the following scenario:

- Attempt to connect to an unreachable server
- The socket keeps trying
- Attempt to connect to another server, calling currentSocket.disconnect and initializing a new connection
- The first socket keeps trying

This [PR](https://github.com/eoinsha/JavaPhoenixChannels/pull/16) fix this by calling cancelReconnectTimer when disconnecting a socket

**Comment by flavius-mester** [comment]
I ran into the same issue.
The PR looks fine for me
