### ISSUE TITLE
Can not connect to localhost

### ISSUE THREAD

**Issue by rafapisco** [eoinsha/JavaPhoenixChannels#18]
I started a new android project using this library, but when I do socket.connect() I get htis error:

**java.net.ConnectException: Failed to connect to localhost/127.0.0.1:4000**

I can access the server at localhost:4000, but for some reason i can't connect to it using your library.

**Comment by bryanjos** [comment]
Try using the ip address instead. I think since you are running on Android, it may not know that you want to connect to the localhost on your machine

**Comment by eoinsha** [comment]
Closing, assuming that this is a dev environment issue.
