### ISSUE TITLE
Inconsistent callbacks (sometimes called, sometimes never called, sometimes empty callback sets, etc)

### ISSUE THREAD

**Issue by alfredbaudisch** [eoinsha/JavaPhoenixChannels#20]
Considering the example chat App, **I tried some network tests**:
- Start without any connection active, then connects later on
- Start connected, wait the socket get connected and the channel joined, then disconnect
- Start connected and while socket connection is ongoing, disconnect
- Start connected, wait for the socket and channel to get connected, then shutdown the server
- Start connected, but with the server offline
- Have everything get connect, then put the application on background

In all cases **I never got consistency from the error,** close and open callbacks.
- Sometimes any or all of the callback sets are empty when they are about to get called by the listener, even although I add them to the sets before connecting, seems like a threading issue
- I never saw channel onError and onClose being called
- Socket onOpen is called 1/2 of the times
- Socket onClose is never called
- Socket onError is never called

**Example:** on a java.net.SocketTimeoutException: timeout, that calls Socket.onFailure, the errorCallbacks was empty, even although I added listeners before connecting.

I'll try to work on a PR, but reporting here in case anyone faced the same issues / already have any fixes in mind.

Example code:
    
    socket = new Socket("ws://..../socket/websocket");

    socket.onOpen(new ISocketOpenCallback() {
        @Override
        public void onOpen() {
            Log.d("CHAT", "socket.onOpen");
        }
    });

    socket.onClose(new ISocketCloseCallback() {
        @Override
        public void onClose() {
            Log.d("CHAT", "socket.onClose");
        }
    });

    socket.onError(new IErrorCallback() {
        @Override
        public void onError(String reason) {
            Log.d("CHAT", "socket.onError");
        }
    });

    socket.connect();

    channel = socket.chan("rooms:lobby", null);

    channel.join()
            .receive("ignore", new IMessageCallback() {
                @Override
                public void onMessage(Envelope envelope) {
                    Log.d(MainActivity.class.getName(), "auth error");
                }
            })
            .receive("ok", new IMessageCallback() {
                @Override
                public void onMessage(Envelope envelope) {
                    Log.d(MainActivity.class.getName(), "join ok");
                }
            });

    channel.on("new:msg", new IMessageCallback() {
        @Override
        public void onMessage(Envelope envelope) {
        }
    });

    channel.onClose(new IMessageCallback() {
        @Override
        public void onMessage(Envelope envelope) {
            Log.d("CHAT", "channel.onClose");
        }
    });

    channel.onError(new IErrorCallback() {
        @Override
        public void onError(String reason) {
            Log.d("CHAT", "channel.onError");
        }
    });

**Comment by alfredbaudisch** [comment]
Well, changing all callbacks sets from WeakHashMap to HashMap solved all the issues:

    private Set<ISocketOpenCallback> socketOpenCallbacks = Collections.newSetFromMap(new HashMap<ISocketOpenCallback, Boolean>());
    private Set<ISocketCloseCallback> socketCloseCallbacks = Collections.newSetFromMap(new HashMap<ISocketCloseCallback, Boolean>());
    private Set<IErrorCallback> errorCallbacks = Collections.newSetFromMap(new HashMap<IErrorCallback, Boolean>());
    private Set<IMessageCallback> messageCallbacks = Collections.newSetFromMap(new HashMap<IMessageCallback, Boolean>());

But to begin with the `WeakHashMaps` shouldn't be garbage collected that fast, on the very beginning of the lifecycle. At the same time I wonder if `WeakHashMaps` are really needed in this case?

**Comment by flavius-mester** [comment]
Thanks @alfredbaudisch it seems I got the same issue like you. I currently get some timeout exceptions which seems to happen on SSL more often. Exceptions from which I cannot recover(reconnect) because the callbacks are never called.
