### ISSUE TITLE
Background Thread or NetworkOnMainThreadException?

### ISSUE THREAD

**Issue by flavius-mester** [eoinsha/JavaPhoenixChannels#22]
Do we need to use the channels in a background thread always?

Is there a plan to make its usage safe in activities using listeners and without worrying about NetworkOnMainThreadException?

I recently got NetworkOnMainThreadException when switching to SSL endpoint. I digged a bit and found it coming from okhttp. Pretty much same issue as here https://github.com/square/okhttp/issues/2017

**Comment by joehudev** [comment]
I also have similar issue. Have you solved this problem?

**Comment by bryanjos** [comment]
I think the advice given in the linked issue for okhttp is the correct advice and should be applied here. Network activity on Android should not be done on the main thread.
