### ISSUE TITLE
FATAL EXCEPTION: OkHttp Dispatcher

### ISSUE THREAD

**Issue by ladybugkiller** [eoinsha/JavaPhoenixChannels#3]
Hi! I've been trying to use Phoenix Channel Client for Android, but get the following error when I try to run my application.

>E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
E/AndroidRuntime: Process: com.example.cc.myapplication, PID: 1611
E/AndroidRuntime: java.lang.AbstractMethodError: abstract method "void com.squareup.okhttp.ws.WebSocketListener.onFailure(java.io.IOException, com.squareup.okhttp.Response)"
E/AndroidRuntime:     at com.squareup.okhttp.ws.WebSocketCall$1.onFailure(WebSocketCall.java:107)
E/AndroidRuntime:     at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:176)
E/AndroidRuntime:     at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:818)
D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
D/: HostConnection::get() 
New Host Connection established 0xf04737d0, tid 1611

So far, I've compiled the client into a .jar file using gradle, and added it to my libs folder. When I tried to run the app, it gave me a missing class error for Jackson Node and okhttp. I added them to my dependencies list, but ended up with the above error which I'm not sure how I should proceed with.

This is my dependencies list
> dependencies {
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:design:23.1.1'
    compile files('libs/JavaPhoenixChannels-0.1.0-SNAPSHOT.jar')
    compile files('libs/JavaPhoenixChannels-0.1.0-SNAPSHOT-javadoc.jar')
    compile 'com.fasterxml.jackson.core:jackson-databind:2.7.0-rc1'
    compile 'com.squareup.okhttp:okhttp-ws:2.6.0'
    compile 'com.squareup.okhttp:okhttp:2.6.0'
}

So far, my main activity only contains up to the following from your example
```
import org.phoenixframework.channels.*;

Socket socket;
Channel channel;

socket = new Socket("ws://localhost:4000/socket/websocket");
socket.connect();

channel = socket.chan("rooms:lobby", null);

channel.join()
.receive("ignore", new IMessageCallback() {
    @Override
    public void onMessage(Envelope envelope) {
        System.out.println("IGNORE");
    }
})
.receive("ok", new IMessageCallback() {
    @Override
    public void onMessage(Envelope envelope) {
        System.out.println("JOINED with " + envelope.toString());
    }
});
```

Do you have any advice as to how I should proceed? Let me know if there's any other details I should provide. Thank you!

**Comment by eoinsha** [comment]
Hi! I'm guessing that this is due to an update in the OkHttp API. When I implemented this, I was still using a release candidate, so it's no surprise that it changed. 

I'll try to take a look at this as soon as I can but I can't guarantee a quick turnaround. If you'd like to have  a look yourself at updating JavaPhoenixChannels to use OkHttp 2.6, I'll gladly accept a PR.
