### ISSUE TITLE
not found: "com.github.eoinsha:JavaPhoenixChannels:0.2"

### ISSUE THREAD

**Issue by jpage4500** [eoinsha/JavaPhoenixChannels#32]
I downloaded the sample android app. When trying to build, I got the gradle error about artifact not found (see title).

I was able to fix this by changing the version to 0.1. Just wanted to note this in case someone else is seeing the same problems

```
    compile('com.github.eoinsha:JavaPhoenixChannels:0.1') {
        exclude module: 'groovy-all'
    }
```

**Comment by jpage4500** [comment]
minor: this link on the main page is also broken (404)

```
For Maven or Gradle-specific instructions detailing how this is done, see the "SET ME UP" section on https://bintray.com/eoinsha/java-phoenix-channels/JavaPhoenixChannels and choose "Resolving artifacts..."
```

**Comment by vrcmarcos** [comment]
Same here!

**Comment by vrcmarcos** [comment]
@jpage4500 I could use changing the maven url to:

`
maven {
    url  "https://dl.bintray.com/javaphoenixchannels/java-phoenix-channels/"
}
`

And the version to 0.1
`
compile('com.github.eoinsha:JavaPhoenixChannels:0.1') {
        exclude module: 'groovy-all'
    }
`

**Comment by bryanjos** [comment]
Good points. I only see 0.1.0 here: https://bintray.com/javaphoenixchannels/java-phoenix-channels/JavaPhoenixChannels. @eoinsha any thoughts?

**Comment by eoinsha** [comment]
The 0.2.0 had been uploaded but I hadn't clicked 'publish'.
Resolved now and updated the bintray link in the `README.md`.
