### ISSUE TITLE
Using Gson instead of Jaxson

### ISSUE THREAD

**Issue by jpage4500** [eoinsha/JavaPhoenixChannels#33]
Hi,

This isn't an issue as it is a question. Have you thought about allowing any JSON serializer like Gson instead of Jaxson? I just noticed it referenced while quickly scanning the Socket.java class.

I'm asking b/c I already use Gson in my app - not because I have anything against Jaxson. It might be perfectly fine to use both - just wanted to ask since ideally I wouldn't need to use both.

```
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.JsonNodeFactory;
import com.fasterxml.jackson.databind.node.ObjectNode;
```

**Comment by eoinsha** [comment]
It was a slight personal preference at the time so there's no big reason. If anyone can make a compelling case to change and submit a PR, I think we're open to that. Given the application here, performance should have a significant bearing on any decision. When Jackson was introduced, it was more about getting a first working cut of Phoenix channels for Android apps up and running. I don't recall if performance was a consideration.
