### ISSUE TITLE
Unit test that connects to Socket works in debug mode, but not regular run.

### ISSUE THREAD

**Issue by virtualandy** [eoinsha/JavaPhoenixChannels#34]
Longshot, but here goes.

We are using this library successfully (so thanks so much for putting it out there!) in an app.

When trying to test some changes to the wss backend, we wrote a little .jar that connects to our server, waits for responses on a channel, etc. That works fine.

I tried moving it into a unit test to keep it a little closer to our app. I've had mixed results.

When I run it in debug mode and step through the breakpoints, it seems to connect to the socket fine, gets messages, etc. When I run it with the regular Run option, our socket connection doesn't seem to happen and the test then fails.

The test looks something like this (ignore terrible formatting please 😸 ):
```java
@Test
public void testWebsocketConnection() { 

  final Socket socket;
  Channel channel;
  final String SERVER =
                "wss://<some_server>/socket/websocket";

        try {
            socket = new Socket(SERVER);
            // Cert problems, so just ignoring
            TrustManager[] trustAllCerts = new TrustManager[]{ new X509TrustManager() {
                public void checkClientTrusted(
                        java.security.cert.X509Certificate[] x509Certificates, String s)
                        throws java.security.cert.CertificateException {
                }

                public void checkServerTrusted(
                        java.security.cert.X509Certificate[] x509Certificates, String s)
                        throws java.security.cert.CertificateException {

                }

                public java.security.cert.X509Certificate[] getAcceptedIssuers() {
                    return new java.security.cert.X509Certificate[]{};
                }
            }
            };

            final HostnameVerifier DO_NOT_VERIFY = new HostnameVerifier() {
                public boolean verify(String hostname, SSLSession session) {
                    return true;
                }
            };

            SSLContext sc = SSLContext.getInstance("TLS");
            sc.init(null, trustAllCerts, new java.security.SecureRandom());
            socket.setSSLSocketFactory(sc.getSocketFactory());
            socket.setHostnameVerifier(DO_NOT_VERIFY);

            socket.connect();
            // This returns 'false'
            System.out.println("Connected? " + socket.isConnected());

            channel = socket.chan("searches:sample-events-uuid", null);

            channel.join()
                    .receive("ok", new IMessageCallback() {
                        @Override
                        public void onMessage(Envelope envelope) {
                            System.out.println("JOINED with: " + envelope.toString());
                        }
                    });
            channel.onError(new IErrorCallback() {
                @Override
                public void onError(String s) {
                    // I don't see this when test fails
                    System.out.println("fail! " + s);
                }
            });
        } catch (Exception e) {
            // This doesn't catch when test fails
            System.out.println("caught something " + e.getLocalizedMessage());
            e.printStackTrace();
        }
}
```
(Code modified in Github UI so may have left in a typo. But as mentioned, something similar passes and the jar runs when this is wrapped in a main and run separately).

Any ideas on what I'm missing? I tried messing with Run configurations in Android Studio 2.2 with no luck.

I realize this is a bad test - the point is just for us to be able to remove @Ignore annotations on these tests and run them when we need to work with backend team to debug. Thanks for any thoughts!

**Comment by bryanjos** [comment]
@virtualandy maybe it is that when it runs without the breakpoints, the test is exiting before the connection is made? I'm thinking you would need some kind of async testing setup. That's just my first thought.

**Comment by virtualandy** [comment]
@bryanjos I'll look into that. I tried some simple `Thread.sleep()` but no dice there. Thanks for the thoughts.

**Comment by bryanjos** [comment]
No problem. If I can get some time, I can write some tests for the project here that might be good examples. Luckily for the rest of the year my Fridays are freed up enough to do some things

**Comment by virtualandy** [comment]
@bryanjos thanks! I threw some comments in #35 so will just close this one out. If I come up with anything, will definitely relay it here.
