### ISSUE TITLE
Invalid README or method definition

### ISSUE THREAD

**Issue by pareeohnos** [eoinsha/JavaPhoenixChannels#44]
I'm not sure if this is more an issue with the README providing incorrect instructions, or a method incorrectly being marked as `private`, but some of the handler methods on a channel are no longer public. The README provides this snippet:

```java
channel = socket.chan("rooms:lobby", null);
channel.join()
...
channel.onClose(new IMessageCallback() {
    @Override
    public void onMessage(Envelope envelope) {
        System.out.println("CLOSED: " + envelope.toString());
    }
});

channel.onError(new IErrorCallback() {
    @Override
    public void onError(String reason) {
        System.out.println("ERROR: " + reason);
    }
});
```

However the `onClose` and `onError` methods are private and thus this fails to compile.
I'm not sure whether it was meant to be made private (as they were public in a previous version) or if the README simply needs updating to show the usage of the `on` method instead.

**Comment by bryanjos** [comment]
Hi, you are correct that the readme is wrong. I'll remove those 2 incorrect method calls. I can update it with the correct use of `on` in those places

**Comment by bryanjos** [comment]
Updated. Thanks for pointing that out!

**Comment by pareeohnos** [comment]
No problem :)
