### ISSUE TITLE
What dependency in build.gradle

### ISSUE THREAD

**Issue by jeandavid** [eoinsha/JavaPhoenixChannels#5]
Hi!

I am quite new to android so I still have to delve into gradle. Until now, if I wanted to use a third party component,  all I had to do was to add a dependency to my build.gradle file ( compile "..").

I tried to do the same with JavaPhoenixChannels: 
`compile('org.phoenixframework.channels:JavaPhoenixChannels:0.1.0-SNAPSHOT')`

This is what you do in the PhoenixChatAndroid example. But when I synchronize, it fails to resolve. 

What dependency should I compile? 

Thank you very much!

**Comment by rubsnick** [comment]
Hey, I'm trying to figure this out myself, It would be beneficial if you included the current version in the readme.

**Comment by jeandavid** [comment]
@rubsnick check this https://github.com/bryanjos/AndroidPhoenixDemo/issues/2

**Comment by bryanjos** [comment]
@eoinsha maybe it would be helpful to publish this so it can be used like a normal java package. I'm not familiar with how to do that. I've been using [jitpack.io](https://jitpack.io/) to pull it in to projects. Or if not, maybe just tag the version in master currently so that users could point to that tag using jitpack.

**Comment by rubsnick** [comment]
@jeandavid  Thank you that seem to have worked well.

**Comment by eoinsha** [comment]
I realise that it has been a while without having a proper release. I hope to address this soon and have versioned release available in a public repo.
If anyone else is willing to help maintain and avoid the bottleneck here, please let me know here. Contributors have kept this going so it would be great to have someone else with committer rights :)

**Comment by bryanjos** [comment]
@eoinsha I'm willing to help out

**Comment by eoinsha** [comment]
@bryanjos I missed your offer of help message on Mar 26! It would be great if you're still willing to help. Let me know and I'll happily add you to the committers. Thanks 👍

**Comment by bryanjos** [comment]
@eoinsha no worries. I've gotten a bit busier since then, but I think I can still help out with issue triage, looking at PRs, and ocassionally sending some as well.

**Comment by bryanjos** [comment]
I guess this can be closed, but definitely need to make a proper release
