### ISSUE TITLE
Token-authentification at socket creation/connection

### ISSUE THREAD

**Issue by PoCk3T** [eoinsha/JavaPhoenixChannels#6]
Hello all,

In Socket.IO, it's super easy to get my token sent for authentification purposes during socket creation :

IO.Options opts = new IO.Options();
opts.forceNew = true;
opts.query = "auth_token=" + authToken;
Socket socket = IO.socket("http://localhost", opts);

How can I do the same thing with the Phoenix Socket ?
Thank you in advance,
Lucas

**Comment by flavius-mester** [comment]
up for this !

**Comment by Pururun** [comment]
What you can do is to include the query parameters in the url, like this:

```
Uri.Builder url = Uri.parse( "http://localhost" ).buildUpon();

url.appendQueryParameter( "auth_token", authToken );

return new Socket( url.build().toString() );
```

**Comment by flavius-mester** [comment]
thanks @Pururun  , it works well

**Comment by eoinsha** [comment]
@PoCk3T does that work well for you? If so, I'll close unless you think there's something else we can do here.
