### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by axelson** [eoinsha/JavaPhoenixChannels#70]
Is this library still maintained? If not are there any active forks?

**Comment by LEECHHE** [comment]
I forked this lib and applied pending PRs. You should add it with jitpack.
https://github.com/LEECHHE/JavaPhoenixChannels

@eoinsha how about assigning new maintainers?

**Comment by sebamateo** [comment]
Thanks @LEECHHE!!! you rock!

**Comment by ScorpiusZ** [comment]
@LEECHHE I am using your version
```
    compile 'com.github.LEECHHE:JavaPhoenixChannels:master-SNAPSHOT'
```

but I got an exception on production evironment

```
java.lang.NullPointerException
at org.phoenixframework.channels.Socket.push(Socket.java:316)
at org.phoenixframework.channels.Push.send(Push.java:165)
at org.phoenixframework.channels.Channel.sendJoin(Channel.java:286)
at org.phoenixframework.channels.Channel.rejoin(Channel.java:218)
at org.phoenixframework.channels.Channel.rejoinUntilConnected(Channel.java:227)
at org.phoenixframework.channels.Channel.access$300(Channel.java:19)
at org.phoenixframework.channels.Channel$8.run(Channel.java:275)
at java.util.Timer$TimerImpl.run(Timer.java:284)
```

It seems that channel rejoin but socket is null here

```
    void send() throws IOException {
        final String ref = channel.getSocket().makeRef();
        log.trace("Push send, ref={}", ref);

        this.refEvent = Socket.replyEventName(ref);
        this.receivedEnvelope = null;

        this.channel.on(this.refEvent, new IMessageCallback() {
            @Override
            public void onMessage(final Envelope envelope) {
                Push.this.receivedEnvelope = envelope;
                Push.this.matchReceive(receivedEnvelope.getResponseStatus(), envelope);
                Push.this.cancelRefEvent();
                Push.this.cancelTimeout();
            }
        });

        this.startTimeout();
        this.sent = true;
        final Envelope envelope = new Envelope(this.channel.getTopic(), this.event, this.payload, ref);
        this.channel.getSocket().push(envelope);
    }
```
should we check socket when Push.push() ?

**Comment by nateboxer** [comment]
@LEECHHE - I would love to use your fork, but no matter what I try, gradle sync fails:

```implementation 'com.github.LEECHHE:JavaPhoenixChannels:master-SNAPSHOT'
implementation 'com.github.LEECHHE:JavaPhoenixChannels:0.2'```

Can you add somewhere here or in your fork the correct path for the gradle file?

Thank you!

**Comment by dpreussler** [comment]
@dsrees would be interested 

@LEECHHE i am getting with this message

```
{"topic":"rooms:TESTROOM","ref":null,"payload":{"user":"testuser","body":"test"},"join_ref":null,"event":"new:msg"
```

getting swallowed as of internal exception. Seems the field is not part of envelope but its what server is sending 
(it might be sth wrong with the server setup, so wanted to check here if its library issue or not)

```
e = {UnrecognizedPropertyException@11309} "com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "join_ref" (class org.phoenixframework.channels.Envelope), not marked as ignorable (4 known properties: "event", "ref", "payload", "topic"])\n 
```

**Comment by dpreussler** [comment]
@LEECHHE  so my issue is the new protocol version. This was fixed by a PR here some time ago:
https://github.com/eoinsha/JavaPhoenixChannels/pull/60
any reason this never made it to your fork?

**Comment by dsrees** [comment]
@eoinsha I would also be interested in taking up maintenance of this repo. Currently I maintain the SwiftPhoenixClient as well and was in the process of making my kotlin implementation available.

**Comment by dsrees** [comment]
I've pushed my [implementation](https://github.com/dsrees/JavaPhoenixClient). Feel free to try it out and give feedback!

**Comment by LEECHHE** [comment]
Hello, guys. I made a new library for phoenix.
https://github.com/chain-partners/kotlinphoenixchannel

It works well on production and is used by a cryptocurrency exchange app. It would be maintained as long as the exchange works. :)
